### ISSUE TITLE
VGMTrans SSEQ cannot extract certain songs

### ISSUE THREAD

**Issue by jimbo1qaz** [vgmtrans/vgmtrans#39] opened 2015-04-11 03:52 UTC
One example is DS Zelda Spirit Tracks's SSEQ_0018 (overworld train theme). VGMTrans locates the tracks properly, but calculates each of their stopTime's as zero, and immediately aborts the MIDI extraction. As a result, I get a MIDI file containing all the tracks, named by hex location, but with no note events whatsoever.

The hex-dump viewing of the SSEQ also recognizes each track as containing no note events.

**Comment by jimbo1qaz** [comment] 2015-04-12 01:57
So here's the bug!
Spirit Tracks overworld theme uses 0x94 jump at the very beginning of each track,
to jump to the relevant song section.

vgmtrans interprets it as a loop point end, and immediately bails out
in both READMODE_ADD_TO_UI and READMODE_FIND_DELTA_LENGTH.

Because READMODE_ADD_TO_UI breaks, the hex dump terminates early.

Because READMODE_FIND_DELTA_LENGTH breaks, deltaLength is set to zero
and the subsequent READMODE_CONVERT_TO_MIDI stopTime is zero,
causing the MIDI conversion to terminate immediately.

The correct way to detect loops is to keep a set of which byte ranges you have already processed,
and abort when you reenter a visited range.

That method won't abort incorrectly whenever the song jumps to an unvisited area.

**Comment by loveemu** [comment] 2015-04-12 03:08
The commit above improves the situation, probably. Can you test it and give a feedback here?

**Comment by jimbo1qaz** [comment] 2015-04-12 03:31
It plays back properly now.
But it still contains neither the intro nor the first-part repeat.
VGMTrans preview has missing/bad notes, the MIDI export is fine.

**Comment by loveemu** [comment] 2015-04-12 04:10
I think so too. (I haven't verify the details, though)

If those missing notes are caused by a CPU-based branch, I want to going to close this issue. If you have an opinion on a CPU-based branch, you can write it on issue #19.

**Comment by jimbo1qaz** [comment] 2015-04-12 04:50
I checked the SSEQ: Each track has a leading unvisited segment (intro skipped by jump), and a later unvisited segment (skipped part A-A loop). Is it possible to modify SSEQ ripping to add custom rip from offset?

**Closed** 2015-04-12 19:11 UTC
Labels: bug
