### ISSUE TITLE
Chrono Cross - Dream's Creation crashes on load

### ISSUE THREAD

**Issue by nyanpasu64** [vgmtrans/vgmtrans#168] opened 2020-05-29 10:17 UTC
**Describe the bug**
When you try to load "Chrono Cross" PSF dump, song "Dream's Creation", it crashes.

**To Reproduce**
Steps to reproduce the problem.
1. Drag "120 Dream's Creation.psf" into the program.

**Expected behavior**
It loads.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - VGMTrans version: latest git refactor c619183878058e0b75172b220eafc4140c961e11
 - VGMTrans log: what's that?
 - Game ROM or music dump SHA-256: 8129DCDCE194D37FE1911F6721F56181D3DCB79ECED8F82452B1053B95FC60D2

**Additional context**

https://github.com/vgmtrans/vgmtrans/blob/a179e4d57fca6b9f814e3a086b4ef99f20de0cd7/src/main/formats/AkaoSeq.cpp#L63-L66

well they're both zero in this song, lmao. It seems this song only uses one instrument or something... it's a music box.

**Comment by loveemu** [comment] 2020-05-29 23:21
I am working on a full rewrite of AkaoSeq parser slowly. I will try to see
what will happen after the rewrite.

**Comment by korobetski** [comment] 2020-05-30 07:35
I wrote a specialized AKAO translator for Vagrant Story largely based on the work of VGMtrans: https://github.com/korobetski/Vagrant-Story-Unity-Parser/blob/master/Assets/VS/Parser/AKAO .cs
MUSIC024.DAT in Vagrant Story has the same problem as "Dream's Creation", no specific instruments or drums, however each music uses a default sound bank, WAVE0005.DAT in the case of Vagrant Story; most music to function properly therefore needs to load two or even three different "banks".
Maybe it's the same for CC, a default bank plus a specialized bank, and when there is no specific bank to load, maybe the default bank is just enough for music .
But maybe the problem is different. :s

**Comment by sykhro** [comment] 2021-06-02 09:09
Should be fixed by #196

**Closed by sykhro** 2021-06-02 09:09 UTC
Labels: Square PS1, bug
