### ISSUE TITLE
Some tracks from the "Puyo Puyo" series crash the prgram

### ISSUE THREAD

**Issue by Pgj1997** [vgmtrans/vgmtrans#103] opened 2017-11-16 20:33 UTC
A few tracks from "Puyo Puyo! 20th Anniversary", "Puyo Puyo! 15th Anniversary", "Puyo Puyo 7" and "Puyo Pop Fever" are recognized by VGMTrans, but crash the program when trying to preview them.

**Comment by sykhro** [comment] 2018-06-08 12:58
Can't reproduce. Which sequences are crashing, exactly?

**Comment by sykhro** [comment] 2019-01-08 21:32
Tried again with every single sequence and no one seemed to crash. Closing.

**Closed by sykhro** 2019-01-08 21:32 UTC
Labels: NDS, bug, research needed
