### ISSUE TITLE
Support for Neopets Darkest Faerie?

### ISSUE THREAD

**Issue by Saehork** [vgmtrans/vgmtrans#110] opened 2018-03-15 21:24 UTC
Let me start by saying, this is a GREAT programme. It's a dream come true for sure, buuuuut

The lack of supported engines leaves SO much to be desired. I went through 16 games and only SEVEN of them worked.

Granted, most of the ones that didn't work were ps2 iso files, but there were even 2 .nds files that were unsupported.

The biggest let down was finding out that my favourite game out of all of these, Neopets The Darkest Faerie was one of the other 9 that didn't work.

I know it isn't easy to take apart sound engines, and I appreciate what's already there, greatly; that's why I'm only asking for one game's engine to be added sometime in the future, and that one would be Neopets.

If anyone's interested, the other 8 that didn't work were:
Spyro Shadow Legacy- NDS
Spore Creatures- NDS
Monster Lab- PS2
Fur Fighters Viggo's Revenge- PS2
Gauntlet Dark Legacy- PS2
Gex 3- N64
Petz Catz 2- PS2
Spyro A Hero's Tail- PS2

**Comment by Harley201** [comment] 2018-03-16 01:00
Check the readme before submitting an issue as N64 isn't supported. Neopets: The Darkest Faerie, AHT, Petz Catz 2, Gauntlet Dark Legacy, Fur Fighters and Monster Lab (Unsure about this one) are not sequenced games, this ripper should only work on sequenced games. Shadow Legacy should rip fine, I'll test that myself later

**Comment by Saehork** [comment] 2018-03-16 05:54
Many thanks for the quick reply, and my apologies, I remembered wrong about n64 support.
May I ask, then, if those games are not sequenced, then are they just looping audio?

**Comment by Harley201** [comment] 2018-03-16 06:32
They are just streamed music yes. Looped audio

**Comment by Saehork** [comment] 2018-03-16 06:41
That... is INCREDIBLY depressing.... Thank you for taking the time to point it out, though, still; I appreciate it.

And about Shadow Legacy, whenever I try to rip it, the programme crashes. The same thing happens with Spore Creatures. I may have jumped the gun and just assumed they were unsupported, but I tried multiple times, could it be an error with my computer then?

**Comment by sykhro** [comment] 2018-03-16 06:43
Crashing is never desired behaviour, I'll investigate

**Comment by Harley201** [comment] 2018-03-16 21:13
I've checked websites for Shadow Legacy and apparently it uses some sort of custom format, I swear I remember ripping it before but I must have remembered wrong, It doesn't crash on my end but it doesn't load anything either. Spore Creatures however does, It loads a couple of soundbanks then crashes at one point. Can't find what specific song it crashes on because the selection box turns completely white when it crashes

**Comment by Saehork** [comment] 2018-03-25 18:28
Is there any way I can help figure out what's going on? I hate the idea of proposing a problem and not at least trying to help in some way, even though most of this is outside my area of expertise.

**Comment by JimmyTheBug** [comment] 2018-05-21 22:55
Saw this post about a month or so ago. is anyone actually trying to figure out about Spore for the ds? I had the same issue, along with Death Jr and the science fair of doom, and Battle of the giants- Dragons, but I couldn't care less about those.

I wanted to get that sweet Spore Creature soundfont, but yeah, it crashes when loading. Has anyone tried creating a dump file and going back to see what the problem was? I don't have anything on my computer that reads dumps, so I can't do it.

Also, I don't think Neopets is streamed audio, because playing the game, there's a lot of audio hiccups it has like the wrong note being played, or a random instrument playing when it isn't supposed to. Doesn't seem like something streamed audio would do.

I'd also like to point out that there are certain places within most areas, that have dynamic music. Like, near a certain spot, more instruments start playing, and I know this CAN be done with streamed audio, but it's hardly done with anything other than sequenced.

**Comment by sykhro** [comment] 2018-06-03 21:40
Spore Creatures is not crashing on my end. Here is a SHA-256 of the ROM I'm using. 
`3ddfe31d19d5c385d7475c19213f3a1649a4adfbbe4c37cfab54ba7577f3ae45 | 2624 - Spore Creatures (Europe) `
Please try with latest master.

**Comment by JimmyTheBug** [comment] 2018-06-04 02:19
I can't seem to figure out how to use master. Is there a guide somewhere?

**Comment by sykhro** [comment] 2018-06-04 15:46
Download from [here](https://ci.appveyor.com/project/loveemu/vgmtrans/build/1.29-qt-port/artifacts)

**Comment by sykhro** [comment] 2018-06-11 14:48
@JimmyTheBug any updates?

**Comment by JimmyTheBug** [comment] 2018-06-11 21:02
Oh, er, I mean, I guess. It seemed like it worked; at the very least, it didn't crash and stuff loaded. I was able to get the soundfont and all, but I started looking into the sequences and, I mean, I was kind of disappointed.

It's nothing on vgmtrans's end, it's just that, I dunno, I couldn't find any of the level music, well, not entirely anyway, it's like each file has the few seconds of several of them, and then nothing, which leads me to believe the soundtrack is half sequenced, half streamed.

Or maybe I'm still not doing something right, I mean, I got the same thing you did, right?
![zombomeme 11062018170046](https://user-images.githubusercontent.com/39503507/41256912-0e510ad2-6d99-11e8-94d4-6e0dbcf0a9c5.jpg)

**Comment by sykhro** [comment] 2018-06-11 21:26
I checked a music dump (.mini2sf) and the only streamed tracks seem to be the main menu, the opening and ending movies. They also sound different compared to what vgmtrans extracts.

Basically all of the sequences make use of conditional statements, so the real problem here is #41.
I'm closing this report, as it looks like the Spore issue is the only valid one.

**Closed by sykhro** 2018-06-11 21:26 UTC
Labels: enhancement, research needed

**Comment by JimmyTheBug** [comment] 2018-06-11 22:01
Wait, no please come back! I'm stupid and desparate😭

 I don't know how to do _aaaannyyy_ of what #41 is saying, but I've gotten this far; is there some kind of tutorial? Or some addition? A script of some kind?

**Comment by sykhro** [comment] 2018-06-11 22:05
Not really, the problem is that vgmtrans currently ignores all the conditional statements found in NDS sequences. The game is most likely using that to loop audio and play different sections. It will be implemented *someday*

**Comment by JimmyTheBug** [comment] 2018-06-11 22:07
O-... oh ._.

I'll be waiting patiently, then. Thank you for your help!

**Comment by jinxynii** [comment] 2023-11-27 16:54
> Check the readme before submitting an issue as N64 isn't supported. Neopets: The Darkest Faerie, AHT, Petz Catz 2, Gauntlet Dark Legacy, Fur Fighters and Monster Lab (Unsure about this one) are not sequenced games, vgmtrans should only work on sequenced games. Shadow Legacy should rip fine, I'll test that myself later

I'm fully aware that this post was made before Neopets was actually decompiled, but it turns out, 90% of the music in it is actually sequenced. Monster860's gamefile reader shows all of the audio tracks, and apart from a few jingles, such as the quest obtain/complete song, and a few others like the "puzzle start" jingle, every song is sequenced through the midi format. You can even download said midis from this viewer and hear the individual instruments from the soundfont the game uses and turn off and on different channels to the song.

Unfortunately, the only thing you *can't* do with this reader is download the soundfont itself.

https://monster860.github.io/ntdf-tools/gamefile_reader.html is the link to that if you're interested. You'll need the gamefile.dat from within the Neopets iso to use it, however.

You can get a bit more data from her NP:TDF editor, which while they cannot be played like they can on the reader, you can get their byte addresses. The link to that is here; https://monster860.github.io/ntdf-editor/
