### ISSUE TITLE
Playback problems with songs that use more than 16 MIDI channels

### ISSUE THREAD

**Issue by gocha** [vgmtrans/vgmtrans#197] opened 2021-03-10 14:40 UTC
**Describe the bug**
Some songs don't play correctly, some sounds are lost or different instruments are used. When a song uses more than 16 MIDI channels, the same MIDI channel can be shared by multiple tracks, resulting in a different sound than expected. As far as I can confirm, the sound output is similar to the result when I export MIDI+SF2 and play it back with foobar2000.

**To Reproduce**
Steps to reproduce the problem.
1. Load Castlevania - Dawn of Sorrow.nds
2. Start playing SDL_BGM_BOSS1_ (Evil Invitation).

**Expected behavior**
[Castlevania: Dawn of Sorrow OST - Evil Invitation - YouTube](https://www.youtube.com/watch?v=NUodpncVH-Q)
You will easily notice that the string ensemble on the first track has been replaced by crash cymbals on the 16th track.

> **To Reproduce**
> Steps to reproduce the problem.
> 1. Load Final Fantasy X: 415 Seymour Battle.minipsf2
> 2. Start playing. You'll notice that some of the first synth melody is missing.
> 3. (Additional step: if you stop and restart playback, the playback result will be different.)
> 
> https://twitter.com/loveemuchan/status/1369657585696055296
> 
> **Expected behavior**
> You will hear the synth sound correctly. In the last release (where DirectMusic is used), the synth will sound correct.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - VGMTrans version: VGMTrans-55393d9c519ba8bad2563eb869a60afa51b53221-master-x86_64-Windows (Qt)
 - VGMTrans log: No errors or warnings
 - Game ROM or music dump SHA-256: I will write if necessary

**Information that may be relevant**
https://github.com/FluidSynth/fluidsynth/pull/677

**Comment by sykhro** [comment] 2021-03-10 17:17
After some digging, it seems like the bug is actually about SF2: the new playback system uses that instead of DLS. Something in the SynthFile -> SF2 conversion is going wrong. To make things worse, it also seems to be random; only random tracks from random games have this kind of problem. There's a whole realm of possibilities here: SF2 not being spec-compliant, numerical errors in conversion, data type mismatches.. it's going to take a while

**Comment by sykhro** [comment] 2021-03-10 17:21
On top of that, it also seems like our DLS files are not compliant either as some playback engines don't recognize them.

**Comment by loveemu** [comment] 2021-03-27 19:16
I don't know FluidSynth at all, so I googled a lot of things. Maybe it has something to do with the fact that the winmidi driver's support for 16+ channels is not included in version 2.1.x, and seems to be updated in 2.2.0? https://github.com/FluidSynth/fluidsynth/pull/677

**Comment by loveemu** [comment] 2021-03-27 19:18
Or do we need a meta-event or something to select a (virtual) MIDI port to ensure that different MIDI channels are used between tracks? (for example: FF 21 01 pp)

**Comment by sykhro** [comment] 2021-03-28 09:12
> I don't know FluidSynth at all, so I googled a lot of things. Maybe it has something to do with the fact that the winmidi driver's support for 16+ channels is not included in version 2.1.x, and seems to be updated in 2.2.0? [FluidSynth/fluidsynth#677](https://github.com/FluidSynth/fluidsynth/pull/677)

I tried playing back the extracted SF2 + midi on fluidsynth on Linux and it still sounds broken, I need to do more digging but I think the problem is somewhere else. Unfortunately FluidSynth rejects our DLS (maybe something is not compliant) so I couldn't try that out yet

**Comment by sykhro** [comment] 2021-05-29 13:12
Since Fluidsynth rejects our DLS and the SF2 don't match them exactly, I've decided to revert this change and keep DirectMidi in the legacy version.

**Comment by loveemu** [comment] 2022-01-27 13:25
Reopen as a Qt/FluidSynth issue. I have confirmed that the Qt version has this problem with SDL_BGM_BOSS1_ in DS Castlevania: Dawn of Sorrow.

**Comment by sykhro** [comment] 2022-01-27 17:35
There was a recent bugfix in upstream FluidSynth that might be related to this. Try downloading the new fluidsynth build from [here](https://github.com/vgmtrans/vgmtrans-ext-win/actions/runs/1757595583), then replace the fluidsynth dll in the vgmtrans folder. Does it sound any different?

**Comment by loveemu** [comment] 2022-01-28 06:52
Replacing the fluidsynth library did not solve the problem. I also figured out why. There are the following reasons:

* Fluidsynth supports many MIDI channel outputs, while its MIDI player doesn't support more than 16 channels of input. (I concluded this after reading [fluid_midi.c](https://github.com/FluidSynth/fluidsynth/blob/v2.2.5/src/midi/fluid_midi.c))
* Standard MIDI file generated by VGMTrans splits the 16+ MIDI channels into individual tracks, but otherwise does not output any meta messages to identify the MIDI device. In general, such data would be interpreted as multiple tracks sharing a single MIDI channel.

## How to represent more than 16 channels in a standard MIDI file

In MIDI 1.0, the number of channels per MIDI port is limited to 16; in MIDI 2.0, the number of channels was extended to 256 with the introduction of the concept of groups, but the SMF we work with today records MIDI 1.0 messages.

As far as I know, there are two types of messages that are often used to select MIDI devices in SMF. Incidentally, [foo_midi](https://gitlab.com/kode54/foo_midi) seems to support both of these.

### FF 21 01 pp (MIDI port; Out of MIDI specification)

Indicates the MIDI device with a number between 0 and 255. This event is not defined in the MIDI specification, but is simple and often used.

### FF 09 LL text (Device Name)

Indicates the name of the MIDI device.

## Possible solution

First of all, we need a mechanism that allows the fluidsynth MIDI player to select more than 16 channels. I'm not familiar with fluidsynth, so I don't know what the best way is. It would be nice if we could add control with `fluid_midi_router` or `fluid_player_set_playback_callback`, but if not, we may need to modify the existing `fluid_midi_router_handle_midi_event` or create a similar function by ourselves.

Also, if necessary, we have to add meta-events to the SMFs generated by VGMTrans, which I think will improve compatibility with MIDI players other than VGMTrans as a side effect.

**Comment by sykhro** [comment] 2022-01-28 12:14
> In MIDI 1.0, the number of channels per MIDI port is limited to 16; in MIDI 2.0, the number of channels was extended to 256 with the introduction of the concept of groups, but the SMF we work with today records MIDI 1.0 messages.

Side note: I would love to add MIDI 2.0 support eventually, but.. are there even any players around?

> First of all, we need a mechanism that allows the fluidsynth MIDI player to select more than 16 channels. I'm not familiar with fluidsynth, so I don't know what the best way is. It would be nice if we could add control with fluid_midi_router or fluid_player_set_playback_callback, but if not, we may need to modify the existing fluid_midi_router_handle_midi_event or create a similar function by ourselves.

FluidSynth docs state:
```
synth.midi-channels

Type
    Integer (int)

Min - Max
    16 - 256

Default
    16 

This setting defines the number of MIDI channels of the synthesizer. The MIDI standard defines 16 channels, so MIDI hardware is limited to this number. Internally FluidSynth can use more channels which can be mapped to different MIDI sources. 
```

We're currently setting it at 48. I'm guessing we need meta events to be able to use them.

**Comment by sykhro** [comment] 2022-01-29 11:00
> After some research, is seems like out best option is to use the sequencer to dispatch events with custom channel mappings to the synth. FluidSynth doesn't support those sysex and using a midi driver is annoying because it's no longer "easily" cross-platform (we'd have to use winmidi on windows, coremidi on macos, alsa_seq or jack on linux, ??? on bsd). The approach I mentioned would also allow to fix #289, by simply avoiding channel 10 altogether.

Basically, this means doing things [like we did with DirectMusic](https://github.com/vgmtrans/vgmtrans/blob/master/src/ui/windows/MusicPlayer.cpp#L630) but making use of `fluid_sequencer_t`. This means getting the `MidiFile` that VGMTrans generates and then processing the events individually, dispatching them to the synth as we prefer.

I think this could work:
- [ ] implement custom midi event processing with `fluid_sequencer_t`
- [ ] add meta events to the MIDIs we export to improve compatibilities with other players
- [ ] implement support for those meta events in our processing function to get the same behaviour as other players

**Comment by sykhro** [comment] 2022-01-29 19:06
Should be fixed in #291 , please test

**Comment by loveemu** [comment] 2022-01-30 02:24
Thank you! I've certainly seen improvements to the points I reported, but I've also identified a number of problems. I'll comment on the pull request later.

**Comment by sykhro** [comment] 2022-02-06 09:19
Has the situation improved?

**Comment by loveemu** [comment] 2022-02-06 10:05
I'm sorry. I didn't have time to do anything prematurely. You're right.

**Comment by CodingPigFromTheBushes** [comment] 2022-09-20 10:12
Hm. I assume this problem still persists? I just tried to export Kirby Mouse Attack to midi and sf2 and some instruments are either missing or sound wrong.

**Comment by sykhro** [comment] 2023-01-30 10:24
Any improvements with latest `master`?

**Comment by sykhro** [comment] 2023-06-26 21:19
Closing this as it should've been fixed with the latest BASS update.

**Closed by sykhro** 2023-06-26 21:19 UTC
Labels: bug, dist:qt, in-app playback
