### ISSUE TITLE
SSEQ parser needs a heuristic to detect infinite loops caused by jumps

### ISSUE THREAD

**Issue by SamusAranX** [vgmtrans/vgmtrans#164] opened 2020-04-26 03:28 UTC
**Describe the bug**
VGMTrans freezes (and eventually crashes) if I attempt to play or export some tracks from ACWW.

The last such track I saw before I gave up trying to export more was SSEQ_0177, but it happens with a bunch of songs, most of which are K.K. tracks.

![screenshot](https://user-images.githubusercontent.com/676069/80296751-e0c6ad00-877d-11ea-92df-0758dfe223b9.png)
**To Reproduce**
Steps to reproduce the problem.
1. Load an ACWW rom
2. Try to play/export SSEQ_0177
3. Observe as the window freezes and Windows fruitlessly tries to find a solution

**Expected behavior**
The track plays/exports

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - VGMTrans version: Both the latest master build (https://ci.appveyor.com/project/mikelow/vgmtrans/builds/29393796/artifacts) and the latest refactored build (https://github.com/vgmtrans/vgmtrans/actions/runs/86669850)
 - VGMTrans log: none
 - ROM SHA1: f1bef752b30dc158d55b48518c80840a7c4586af

**Comment by sykhro** [comment] 2020-04-26 10:01
Tried both US (matching your SHA1) and EU version, can't seem to reproduce.
Please generate a process dump with [this tool](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) launching it like this
`procdump -h VGMTrans.exe vgmtrans-crash.dmp`

**Comment by SamusAranX** [comment] 2020-04-26 11:02
Here you go. The procdump command you posted didn't work, so I substituted the process ID of a freshly started vgmtrans instance instead.

[vgmtrans-crash.zip](https://github.com/vgmtrans/vgmtrans/files/4535162/vgmtrans-crash.zip)

**Comment by SamusAranX** [comment] 2020-04-26 11:13
I just made my own build using the master branch and the issue magically disappeared. 🤔 

I recently had to install a bunch of *ancient* C++ redistributables for Lego Racers to work, could this issue be connected to that? I don't have much experience with C++ and its intricacies.

**Comment by sykhro** [comment] 2020-04-26 11:21
You might have a corrupted library file somewhere. It's still very strange though. The refactor branch binary uses c++17 and some fairly new features so it shouldn't even care about old redist packages. The legacy version might. 
I will try to investigate your coredump in a clean Windows environment, but the issue might be related to your setup.

**Comment by SamusAranX** [comment] 2020-04-26 13:02
Never mind, I managed to cause a freeze while the debugger was attached. Curiously, debug builds don't freeze, it's only the release buils that do.

Hitting the Break All button while the program's frozen seems to indicate that it gets stuck in the while loop in `MidiTrack::PurgePrevNoteOffs` in MidiFile.cpp.
![image](https://user-images.githubusercontent.com/676069/80308304-83a71780-87ce-11ea-8257-9772ab8c821a.png)

I don't know enough about the inner workings of vgmtrans to meaningfully dissect this problem, but I hope this information helps.

**Comment by sykhro** [comment] 2020-04-26 13:21
I haven't done much work in that area of VGMTrans (yet) but that code seems fragile.
Remove everything in that function and replace it with
`prevDurNoteOffs.erase(std::remove_if(prevDurNoteOffs.begin(), prevDurNoteOffs.end(), [absTime](NoteEvent *e) { return e->AbsTime <= absTime; }), prevDurNoteOffs.end());`
You might have to `#include <algorithm>` at the top of the file

**Comment by SamusAranX** [comment] 2020-04-26 13:32
> that code seems fragile
Tell me about it 😅

Before I inserted your code, Visual Studio threw an exception instead of the program just freezing that implied that pointers weren't being initialized properly and pointed to garbage instead, but I can't reproduce it. Seeing as one of the differences of debug and release mode is that in debug mode, pointers get properly initialized by the debugger, I'd say that's the problem.

I tried your code, but it also freezes the program. I can only assume that `prevDurNoteOffs` is garbage at this point.

**Comment by sykhro** [comment] 2020-04-26 13:41
Does it halt in the same place?
`prevDurNoteOffs` is initialized properly and with the code I gave you it shouldn't run into iterator invalidation issues. Are the steps to reproducing it the same as what you wrote in the opening post?

**Comment by SamusAranX** [comment] 2020-04-26 17:16
The steps haven't changed, it's still the same set of MIDI files that makes it freeze. 

With your code, the program appears to halt deep in STL code, namely something called "xutility":
![image](https://user-images.githubusercontent.com/676069/80314486-068d9980-87f2-11ea-9174-6c1c98e4ab08.png)

There's no exception message, only what Visual Studio can show me when I hit Break All.

**Comment by sykhro** [comment] 2020-04-26 17:57
> The program doesn't completely halt, it just gets lost in some loop somewhere, so the UI becomes non-responsive

I'm working on making the thing multi-threaded, slowly getting there

> At a rate of about 120 KB per second, the program's memory usage steadily increases, so something is clearly happening, it's just not what should be happening.

Getting an infinite loop inside STL code is _really_ strange.
I wonder if this slightly different version would help
`prevDurNoteOffs.erase(std::remove_if(prevDurNoteOffs.begin(), prevDurNoteOffs.end(), [absTime](NoteEvent *e) { return e && e->AbsTime <= absTime; }), prevDurNoteOffs.end());`.
I can't seem to find any memory corruption issues at least when compiling with gcc or clang on Linux. I'll try MSVC on Windows shortly.

As an extreme measure, if the above makes no difference, would be to stub the function to see what happens next.

**Comment by SamusAranX** [comment] 2020-04-26 17:59
With that snippet, the application also locks up, though hitting Break All makes Visual Studio say this:

> Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code).

**Comment by sykhro** [comment] 2020-04-26 18:43
> As an extreme measure, if the above makes no difference, would be to stub the function to see what happens next.

(by this I meant the whole function, not just the lambda)

> Unhandled exception at 0x75634192 in VGMTrans_WTL.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x010FECB0.

Uh, this means an allocation failed. It would be great if you could get a call stack that leads to this.

There's a couple options here:
a) Something is out of control requesting a _huge_ allocation
b) You're out of memory
c) Something else is corrupting the memory
d) There's a bug in the STL

**Comment by sykhro** [comment] 2020-04-26 19:13
Can't reproduce with the precompiled binaries on Windows 10. 
What version of the build tools are you using to compile? v140?

**Comment by SamusAranX** [comment] 2020-04-26 20:56
> (by this I meant the whole function, not just the lambda)

I commented out the entirety of the PurgePrevNoteOffs function, leaving it empty. I assumed that's what you meant.

> It would be great if you could get a call stack that leads to this.

![image](https://user-images.githubusercontent.com/676069/80319445-81fe4380-8810-11ea-8e4b-9189e310877f.png)
This is all I could get.

In LoadTracksMain, line 243, there's this: 
![image](https://user-images.githubusercontent.com/676069/80319514-e02b2680-8810-11ea-945b-88fad356c264.png)

> What version of the build tools are you using to compile? v140?

v142. Visual Studio complained that it couldn't find v140 and offered to auto-upgrade to v142, since that's apparently what was on my machine.

**Comment by sykhro** [comment] 2020-04-26 22:26
I'll try to reproduce with v142 then. Given that call stack I'd say that we're officially past the simple-fix stage now. I guess you could add `assert(aTracks.size() == nNumTracks)` and do some digging. Converting SSEQ_117 yields aTracks.size() = nNumTracks = 14 on my end

**Comment by SamusAranX** [comment] 2020-04-26 23:03
Damn, I had hoped this wouldn't be the case. I'd love to help, but I just don't have the knowledge required to dig into this.

You mentioned Linux earlier. Is vgmtrans usable on Linux? If so, are there any prebuilt binaries anywhere or would I have to create a build myself? I need these MIDIs for a silly little side project and I could just use the Linux version if one existed.

**Comment by sykhro** [comment] 2020-04-26 23:16
You can grab a Linux build (AppImage format) from the Actions tab. Building it yourself is also very easy if you want to go down that route (Wiki has the info on how to do it)

**Comment by SamusAranX** [comment] 2020-04-26 23:33
I just tried the latest macOS build from the Actions tab and it too locks up when trying to extract SSEQ_0177 (curiously called "SSEQ_177" without the zero padding). I think I can rule out weirdness in my Windows setup now.

You were right when you said we were beyond the simple-fix stage 😬

**Comment by sykhro** [comment] 2020-04-27 06:55
Apologies, I've been testing "SSEQ_117" instead this whole time. I hope to be able to reproduce it now

**Comment by sykhro** [comment] 2020-04-27 09:19
Okay, I can reproduce this. SSEQ_177 has two tracks: the first one seems normal, the second one is significantly shorter and has basically just 3 notes, a bunch of conditionals and a jump. The parser is entering an infinite loop when dealing with the jump, just like #45. A fix similar to last time is possible but I'll take a couple days to see if we can rewrite the conditional bits to be more solid (and maybe solve #41 once for all)

**Comment by sykhro** [comment] 2020-04-27 10:48
(no, we're not trying to solve the halting problem)

**Comment by sykhro** [comment] 2020-04-27 11:01
@SamusAranX as a workaround, you can change the `return true` to `return false` in `SeqTrack::AddLoopForever`

**Comment by sykhro** [comment] 2020-04-27 16:52
Fixed by 33e840d5f693f85073a32e71d6732e51d31ab79b

**Closed by sykhro** 2020-04-27 16:52 UTC
Labels: NDS, feature set

**Comment by SamusAranX** [comment] 2020-04-27 22:44
Thanks for the workaround! As a side note: While vgmtrans doesn't freeze anymore, all generated MIDI files that would've caused a freeze before will contain invalid metadata now. Here's foobar2000 claiming that SSEQ_0177 (a roughly 42-second track) is almost 2 hours long:  
![image](https://user-images.githubusercontent.com/676069/80427592-68c8c600-88e8-11ea-8d4e-d859444e7df8.png)

Luckily, this doesn't matter much for my purposes. I'm just happy these tracks get extracted at all. 😊
